name: Deploy to Azure

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}

      - name: Pull Latest Changes
        run: |
          ssh -o StrictHostKeyChecking=no -A -tt ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} "cd /home/ardhanurfan/shoes_shop_api && git pull"

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      - name: SSH into Azure VM and Build and Run Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no -A -tt ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_IP }} "cd /home/ardhanurfan/shoes_shop_api && docker-compose up -d --build"
